name: Release

on:
    release:
        types: [created]

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Provision
              run: sudo apt-get install -y libpcsclite1 libpcsclite-dev pcscd
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16
                  registry-url: https://npm.pkg.github.com/
                  scope: "@caname-dev"
            - uses: actions/cache@v2
              id: client-yarn-cache
              with:
                  path: "node_modules"
                  key: client-yarn-${{ hashFiles('yarn.lock') }}
            - run: yarn install
              if: steps.client-yarn-cache.outputs.cache-hit != 'true'
            - run: yarn build
            - run: node test/_node-version-test.js
            - run: yarn test
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GH_ACCESS_TOKEN}}
